services:
  - type: web
    name: aramco-review-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://Shahnawaz2003:Shahnawaz2003@cluster0.wxtwjas.mongodb.net/aramco_review?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGO_DBNAME
        value: aramco_review
      - key: JWT_SECRET
        fromSecret: jwt_secret
      - key: NODE_ENV
        value: production
  - type: web
    name: aramco-review-frontend
    env: static
    rootDir: client
    buildCommand: npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://aramco-review-backend.onrender.com/api
